/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'training-stop-handler': EventHandler<never, never>
    'training-processor': EventHandler<never, { topic: 'metrics-update'; data: never }>
    'synthesis-processor': EventHandler<never, never>
    'metrics-updater': EventHandler<never, never>
    'evaluation-processor': EventHandler<never, never>
    'dataset-processor': EventHandler<never, never>
    'training-stop': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'stop-training'; data: never }>
    'training-list': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'training-detail': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'training-delete': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'training-create': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'start-training'; data: never }>
    'test-state': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'test-simple': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'test-request': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'synthesis-create': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'process-synthesis'; data: never }>
    'models-list': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'health': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'health-api': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'evaluation-create': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'process-evaluation'; data: never }>
    'datasets-list': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'datasets-create': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'process-dataset'; data: never }>
    'inference-generate': ApiRouteHandler<Record<string, unknown>, unknown, never>
  }
    
}